theme: minima
title: Jiaxing's Data Analysis Blog
author: Jiaxing
description: A blog showcasing my data analysis projects and reports.

minima:
  social_links:
    github: Jiaxing0506
show_excerpts: true